/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/gmail`; params?: Router.UnknownInputParams; } | { pathname: `/qq`; params?: Router.UnknownInputParams; } | { pathname: `/tencent`; params?: Router.UnknownInputParams; } | { pathname: `/163`; params?: Router.UnknownInputParams; } | { pathname: `/126`; params?: Router.UnknownInputParams; } | { pathname: `/outlook`; params?: Router.UnknownInputParams; } | { pathname: `/microsoft`; params?: Router.UnknownInputParams; } | { pathname: `/exchange`; params?: Router.UnknownInputParams; } | { pathname: `/other`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}${'/(home)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}${'/(profile)'}/edit` | `/edit`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}${'/(profile)'}/profile` | `/profile`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}${'/(trend)'}/statistics` | `/statistics`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}${'/(wallet)'}/wallet` | `/wallet`; params?: Router.UnknownInputParams; } | { pathname: `/+not-found`, params: Router.UnknownInputParams & {  } } | { pathname: `/details/[id]`, params: Router.UnknownInputParams & { id: string | number; } };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/gmail`; params?: Router.UnknownOutputParams; } | { pathname: `/qq`; params?: Router.UnknownOutputParams; } | { pathname: `/tencent`; params?: Router.UnknownOutputParams; } | { pathname: `/163`; params?: Router.UnknownOutputParams; } | { pathname: `/126`; params?: Router.UnknownOutputParams; } | { pathname: `/outlook`; params?: Router.UnknownOutputParams; } | { pathname: `/microsoft`; params?: Router.UnknownOutputParams; } | { pathname: `/exchange`; params?: Router.UnknownOutputParams; } | { pathname: `/other`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}${'/(home)'}` | `/`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}${'/(profile)'}/edit` | `/edit`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}${'/(profile)'}/profile` | `/profile`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}${'/(trend)'}/statistics` | `/statistics`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}${'/(wallet)'}/wallet` | `/wallet`; params?: Router.UnknownOutputParams; } | { pathname: `/+not-found`, params: Router.UnknownOutputParams & {  } } | { pathname: `/details/[id]`, params: Router.UnknownOutputParams & { id: string; } };
      href: Router.RelativePathString | Router.ExternalPathString | `/gmail${`?${string}` | `#${string}` | ''}` | `/qq${`?${string}` | `#${string}` | ''}` | `/tencent${`?${string}` | `#${string}` | ''}` | `/163${`?${string}` | `#${string}` | ''}` | `/126${`?${string}` | `#${string}` | ''}` | `/outlook${`?${string}` | `#${string}` | ''}` | `/microsoft${`?${string}` | `#${string}` | ''}` | `/exchange${`?${string}` | `#${string}` | ''}` | `/other${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}${'/(home)'}${`?${string}` | `#${string}` | ''}` | `/${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}${'/(profile)'}/edit${`?${string}` | `#${string}` | ''}` | `/edit${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}${'/(profile)'}/profile${`?${string}` | `#${string}` | ''}` | `/profile${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}${'/(trend)'}/statistics${`?${string}` | `#${string}` | ''}` | `/statistics${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}${'/(wallet)'}/wallet${`?${string}` | `#${string}` | ''}` | `/wallet${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/gmail`; params?: Router.UnknownInputParams; } | { pathname: `/qq`; params?: Router.UnknownInputParams; } | { pathname: `/tencent`; params?: Router.UnknownInputParams; } | { pathname: `/163`; params?: Router.UnknownInputParams; } | { pathname: `/126`; params?: Router.UnknownInputParams; } | { pathname: `/outlook`; params?: Router.UnknownInputParams; } | { pathname: `/microsoft`; params?: Router.UnknownInputParams; } | { pathname: `/exchange`; params?: Router.UnknownInputParams; } | { pathname: `/other`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}${'/(home)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}${'/(profile)'}/edit` | `/edit`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}${'/(profile)'}/profile` | `/profile`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}${'/(trend)'}/statistics` | `/statistics`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}${'/(wallet)'}/wallet` | `/wallet`; params?: Router.UnknownInputParams; } | `/+not-found` | `/details/${Router.SingleRoutePart<T>}` | { pathname: `/+not-found`, params: Router.UnknownInputParams & {  } } | { pathname: `/details/[id]`, params: Router.UnknownInputParams & { id: string | number; } };
    }
  }
}
